### ISSUE TITLE
streamlit cloud deployment?

### ISSUE THREAD

**Issue by AbubakrChan** [tonykipkemboi/trip_planner_agent#1]
I deployed the exact same code on streamlit cloud but got this error:
2024-02-12 18:14:30.956 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/trip_planner_agent/streamlit_app.py", line 1, in <module>

    from crewai import Crew

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/__init__.py", line 1, in <module>

    from crewai.agent import Agent

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agent.py", line 22, in <module>

    from crewai.agents import (

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agents/__init__.py", line 2, in <module>

    from .executor import CrewAgentExecutor

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agents/executor.py", line 16, in <module>

    from crewai.utilities import I18N

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/__init__.py", line 4, in <module>

    from .rpm_controller import RPMController

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 10, in <module>

    class RPMController(BaseModel):

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 15, in RPMController

    _timer: threading.Timer | None = PrivateAttr(default=None)

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

2024-02-12 18:14:31.324 503 GET /script-health-check (10.12.201.83) 372.94ms

2024-02-12 18:14:35.979 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/trip_planner_agent/streamlit_app.py", line 1, in <module>

    from crewai import Crew

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/__init__.py", line 1, in <module>

    from crewai.agent import Agent

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agent.py", line 22, in <module>

    from crewai.agents import (

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agents/__init__.py", line 2, in <module>

    from .executor import CrewAgentExecutor

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/agents/executor.py", line 16, in <module>

    from crewai.utilities import I18N

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/__init__.py", line 4, in <module>

    from .rpm_controller import RPMController

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 10, in <module>

    class RPMController(BaseModel):

  File "/home/adminuser/venv/lib/python3.9/site-packages/crewai/utilities/rpm_controller.py", line 15, in RPMController

    _timer: threading.Timer | None = PrivateAttr(default=None)

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Any ideas?
thanks

**Comment by tonykipkemboi** [comment]
I will look into this issue.

**Comment by AbubakrChan** [comment]
> I will look into this issue.

It was because of the python version.
The Python version should be >3.10
